version: "3.8"
services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
  articleapi:
    container_name: articleapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"