version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    # networks:
    #   - default
    ports:
    - "8080:8080"